---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rober33/public_html/artisticinteriorsma
    - export IMAGES_ROOT=/home/rober33/artistic_interiors_photos
    - export IMAGES_TYPES=(bathrooms kitchens more)
    # Clean up old code
    - /bin/rm -rf ${DEPLOYPATH}/*
    # Put in new code
    - /bin/cp -R src/* ${DEPLOYPATH}
    # soft link images in
    - ln -s /home/rober33/artistic_interiors_photos/bathrooms ${DEPLOYPATH}/gallery/bathrooms/images
    - ln -s /home/rober33/artistic_interiors_photos/kitchens ${DEPLOYPATH}/gallery/kitchens/images
    - ln -s /home/rober33/artistic_interiors_photos/more ${DEPLOYPATH}/gallery/more/images
    # soft link specials in
    - ln -s /home/rober33/artistic_interiors_photos/specials/special.jpg ${DEPLOYPATH}/specials/images/special.jpg
